### ISSUE TITLE
Importing MSE

### ISSUE THREAD

**Issue by mahugnon** [moosetechnology/Midas#1]
PB: Currently, when importing mse, MoosePanel try to search entities read in the mse file in a default mooseModel.   As each famixMetaModel has its own model now, the importing fell because entities are not found.
S: MooseModel should allow the user to choose one of the existing models in the image

**Comment by badetitou** [comment]
@mahugnon It is fixed right now ^^
here: https://github.com/moosetechnology/Midas/commit/aa7ceb6bc4f5aa3d09e2c0f6fa5ef66a86de2146
