### ISSUE TITLE
Export browser: Toggle button behavior is faulty

### ISSUE THREAD

**Issue by ClotildeToullec** [moosetechnology/Midas#107]
It should update the browser to show the "Comments" column.
Not possible yet with spec. [https://github.com/pharo-spec/Spec/issues/1052](https://github.com/pharo-spec/Spec/issues/1052)

**Comment by NicolasAnquetil** [comment]
Not sure we need a browser just for exporting entities.
Or maybe if you want it to become a report generator, but just exporting could be a menu option on an entry of the Logger

**Comment by ClotildeToullec** [comment]
@mahugnon told us he needed to comment entities before exporting them. 
I figured it would be easier in an ad hoc browser.
My idea is: we could improve it by allowing the user to choose what they want to export (properties values, metrics, tags etc).
It could become a report generator, yes. For that we need to define our needs and decide more precise specifications
