### ISSUE TITLE
MiInspector: bug displaying with FamixStAnnotationType

### ISSUE THREAD

**Issue by NicolasAnquetil** [moosetechnology/Midas#114]
Create a Famix model including methods with pragma (e.g. all Rubric packages)

Find one FamixStInstanciationType

Inspect it: Error with MiTreeBrowser

**Comment by NicolasAnquetil** [comment]
The bug also appears for other kinds of entities (ex: FamixStGlobalVariable, FamixStMethod)

**Comment by jordanmontt** [comment]
I cannot reproduce this anymore. Can you @NicolasAnquetil ? Or should we close this issue?
