### ISSUE TITLE
Inspecting an entity from Moose tool should open the Moose Inspector

### ISSUE THREAD

**Issue by badetitou** [moosetechnology/Midas#124]
Today, when executing _Inspect_ on a moose entity from a moose tool. It opens the default inspector.
It should open the moose inspector.

(gif shows the incorrect behavior)
![bug](https://user-images.githubusercontent.com/6225039/117670479-3793fe80-b1a8-11eb-8176-097b97cc1053.gif)

**Comment by NicolasAnquetil** [comment]
Yes.
Will one of you do it?

**Comment by ClotildeToullec** [comment]
I agree !

**Comment by NicolasAnquetil** [comment]
from any MooseTool' menu it should always be the MooseInspector, not the default inspector
Ideally this MooseInspector would listen to the same bus(es) than the tool from which it is opened
