### ISSUE TITLE
Newbie (to Midas) can't figure out how to load a model...

### ISSUE THREAD

**Issue by fuhrmanator** [moosetechnology/Midas#149]
I'm new to Midas and installed it following the ReadMe. Being a user of Moose, I expected some menu to load a model, but couldn't find anything. What am I missing here? 

![image](https://user-images.githubusercontent.com/7606540/119273608-b2faa480-bbd9-11eb-97e4-039ac1ceee33.png)

**Comment by NicolasAnquetil** [comment]
hummm, this is an old version of the menus.
Using the latest version (9) I have these menus:
![newMenu](https://user-images.githubusercontent.com/14889146/119323916-813c1900-bc7f-11eb-9638-7a88c6f71b6c.png)

**Comment by fuhrmanator** [comment]
Ok, but I followed the the readme. It seems like the latest Moose Jenkins build is not up to date.

**Comment by NicolasAnquetil** [comment]
It's because you did not choose the latest build :-)
- I pointed the wiki to the Moose ReadMe, it's one more click for the reader, but one less place to update for us (we are a small team)
- I specified that it is usually best to choose the latest version even if it reads "development"

**Comment by fuhrmanator** [comment]
All the builds are "development." 

I think the Readme image (animated GIF) shows to take the latest **successful** build, which is many versions away:

![image](https://user-images.githubusercontent.com/7606540/119395327-5793e980-bca1-11eb-9118-21bed30cb1e7.png)

I think you're saying to take the latest build, ignoring the "successful" one (which isn't updated automatically)?

**Comment by badetitou** [comment]
Hello, 

The Readme of Midas should be updated.
The Jenkins builds are not used anymore.

@fuhrmanator, you can now go in "Official distributions" >> "Moose Suite 9.0". And you'll get the latest working Midas version inside the Moose image.

We decided to stop using Jenkins because it was too time-consuming to support Jenkins + Travis + GitHub actions.
Today, we use only GitHub Actions

**Comment by fuhrmanator** [comment]
> @fuhrmanator, you can now go in "Official distributions" >> "Moose Suite 9.0". And you'll get the latest working Midas version inside the Moose image.

Once I update my PharoLauncher, I can see this :)

**Comment by badetitou** [comment]
Before closing this issue. We have to fix the Midas readme

**Comment by badetitou** [comment]
Sorry... It was done
