### ISSUE TITLE
MiNoSelectedElement should not appear in the log

### ISSUE THREAD

**Issue by badetitou** [moosetechnology/Midas#15]

**Comment by NicolasAnquetil** [comment]
and same for UndefinedObject

and maybe if there are two consecutive entries with the same entities, we don't create the second one

**Comment by ClotildeToullec** [comment]
Fixed in [https://github.com/moosetechnology/Midas/commit/a8a4f0e72ab102ec5550bc546290e520181de2b0](url)

**Comment by NicolasAnquetil** [comment]
There are sill 'nil's  appearing in the logger ?

**Comment by ClotildeToullec** [comment]
I can fix this but i need to know how do we want to react when a browser tries to propagate nil ?
- Do nothing
- Throw an exception (MiNoSelectedItem ?) from MiLogger ?

Maybe we should add a test to assert that no browser can propagate nil.

**Comment by badetitou** [comment]
I think you should stop the propagating at the #globallySelect level
it will be easier

**Comment by NicolasAnquetil** [comment]
propagate can be a toggle / checkbox, but it will not be easier.
We have to allow automatic propagation, otherwise we need to: do something+click "propagate" ; do something else + click "propagate" ==> too much clicking

So we need automatic propagation, so removing propagation on #globallySelect will be necessary somehow.

**Comment by NicolasAnquetil** [comment]
Note1: this discussion is linked to #50 

Note2: Stephane called it "a bus" where every "selected" entity is sent and all browsers listen.
I like the analogy.

May be we can reify it and start to have different buses: one-entity , group-of-entities

Another idea was to be able to create buses dynamically and attache different tools to different buses.
That would allow to explore different actions in // with several instances of the same tools on different buses
