### ISSUE TITLE
Impossible to insert a query between two existing queries 

### ISSUE THREAD

**Issue by enwiro** [moosetechnology/Midas#160]
It would be nice to be able to insert a query between two existing queries in the queries browser.

For example, if want to filter methods for a specific one just after "Methods", in this case :
![image](https://user-images.githubusercontent.com/58632394/119959490-55cd6d00-bfa4-11eb-872b-1f47448e1b46.png)

**Comment by jordanmontt** [comment]
Hi @enwiro, I don't know if I understand you but I think what you are saying is in fact possible.

Is this what you mean?
![image](https://user-images.githubusercontent.com/33934979/120338358-b0880100-c2e3-11eb-999e-0b7fea789e5b.png)

**Comment by jordanmontt** [comment]
Also, this queries browser will be removed in the future. Now we have a new queries browser. You can find it in the Moose menu (New queries browser)

**Comment by enwiro** [comment]
Ok, it's true that if it has to be deleted, it's a bit silly. However, I wasn't talking about creating a new query from a node but about inserting a node into an existing query.
For example, if I want to insert a new node in the nth position of the chain, I have to redo all the queries after this nth position.
Is that clearer?

**Comment by jordanmontt** [comment]
Ok thanks! Now I understand
