### ISSUE TITLE
Trying to open the new queries browser fails

### ISSUE THREAD

**Issue by jordanmontt** [moosetechnology/Midas#164]
If you try to open the new queries browser, the debugger is opened with this exception:
![image](https://user-images.githubusercontent.com/33934979/120013740-a8248300-bfd0-11eb-88f1-f5f329c698c9.png)

This is because `isNegated:` is defined in `FAMIXPreprocessorIfdef` class. That class is not part of the hierarchy of `FQAbstractQuery`

**Comment by jordanmontt** [comment]
@NicolasAnquetil

**Comment by NicolasAnquetil** [comment]
The #isNegated: method was defined and integrated in Famix-Queries.
May be the CI did not have time to built a Moose version with latest Famix-Queries ?
Or may be a configOf points to a hard-coded version number ?

Let see in a day if the problem is still there

**Comment by jordanmontt** [comment]
Yes, now it works like a charm!
