### ISSUE TITLE
MooseInspector broken ?

### ISSUE THREAD

**Issue by NicolasAnquetil** [moosetechnology/Midas#175]
On fresh moose 9, MooseInspector gave me DNU on openning

![image](https://user-images.githubusercontent.com/14889146/123246144-c4d7ac00-d4e5-11eb-8b5c-386aba5b9132.png)

**Comment by ClotildeToullec** [comment]
Fixed by 6e1f7fee12f65a1a44a2f98b81bb87e3b4de3e77
