### ISSUE TITLE
Mi export browser when is opened the columns are too tight 

### ISSUE THREAD

**Issue by jordanmontt** [moosetechnology/Midas#209]
![Screenshot 2021-07-15 at 10 40 54](https://user-images.githubusercontent.com/33934979/125758337-d8c09854-27f4-4d08-93f3-372832b79d4b.png)

As it is shown in the picture, the columns are too tight and nothing can be understood. Maybe is better to display the items vertically instead of horizontally?

**Comment by ClotildeToullec** [comment]
I'm not sure changing the display will make it better: if there is a lot of entities, we will have the same problem.
I should probably limit the number of properties displayed (at least when opening the browser, then users can add some if needed).

**Comment by jordanmontt** [comment]
If we display the items vertically we will not have the problem.
Something like:

|Property name | Value |
| -------------- | ------ |
| containsReplicas | true |
| duplicationRate | 0 |
| fanIn | 0 |
| fanOut | 0 |

... and so on

**Comment by ClotildeToullec** [comment]
Yes we will, because the "Value" column is available for each entity. In your example, there is only 1 entity, but if we show all classes in a model, we could have thousands of columns, 1 per class.

**Comment by jordanmontt** [comment]
Yes you are right... I do not what it can be done. You can close this issue if you want

**Comment by ClotildeToullec** [comment]
No, you're right this is a problem. I think I will limit the number of displayed properties when the browser is open
