### ISSUE TITLE
MiModelRootBrowser fails to start first time

### ISSUE THREAD

**Issue by NicolasAnquetil** [moosetechnology/Midas#28]
... because there is no last select entity (no models, logger empty, ...)

```smalltalk
MiAbstractBrowser class >> #runMe
	<script>
	self new
		openWithSpec;
		"open with the last select entity"
		selectEntity: MiApplication current logger logs last entity
```

**Comment by badetitou** [comment]
I've just downloaded a fresh image and try to execute "runMe" and no error raised

**Comment by NicolasAnquetil** [comment]
How did you load it? (baseline? default ?)
What image? (Moose8?)

No model in the image ?

**Comment by badetitou** [comment]
I used the image produced by jenkins
![image](https://user-images.githubusercontent.com/6225039/84029796-47510480-a993-11ea-89f3-3456327fe4c5.png)

no model in the image

**Comment by badetitou** [comment]
This error is also strange to me because we have a test that ensure we can open all browsers without error event if no model is installed. 
But, if in fact there is an error, we must improve our tests

**Comment by ClotildeToullec** [comment]
I had the same bug with FQ browser. 
Maybe we should have a default value (an empty MooseGroup ?) when no entity has ever been selected ?

**Comment by badetitou** [comment]
In this case, I would prefer to have an exception (MiEmptyLogException) or something

**Comment by NicolasAnquetil** [comment]
Whatever, this should not produce an error for the user.
Imagine a new user, opening the browsers (any browser). He does not have a model because he does not even know what moose is. First thing he gets is an error !!!!

**Comment by badetitou** [comment]
I agree. This is why we have a test that checks this feature :-)

**Comment by ClotildeToullec** [comment]
Ok, I worked on famix queries browser so Midas tests do not fail anymore. 
Problem is, the tests fail only if no entity is selected.

Should we call ```MiApplication current logger clean.``` in setUp method to be sure that no entity is previously selected ? 
Then if you run the tests, you clear the current log, which maybe you did not want.

**Comment by NicolasAnquetil** [comment]
Not sure I understand but, the tests should run on their own MiApplication, not use the same as the user.
Otherwise the state of the image influences the tests and the tests influence the image. We don't want that

**Comment by ClotildeToullec** [comment]
Now tests run with an empty log and previous log is restored after tests.
[https://github.com/moosetechnology/Midas/commit/15ae55c700d187417a5811909f6a47832fcd7aee](url).
This way the tests always run in the same condition and should always fail in the case you described.
