### ISSUE TITLE
QueryBrowser, resultOfCurrentQuery pane is not ordered

### ISSUE THREAD

**Issue by NicolasAnquetil** [moosetechnology/Midas#30]
clicking repeatedly on the (initial) "Model" query changes the content of this pane, actually the order of the "entities" listed.
This is unsettling

Note: ALWAYS order displayed lists. The actual order may not matter but make sure there is one

**Comment by ClotildeToullec** [comment]
Fixed in FamixQueries commit [https://github.com/moosetechnology/FamixQueries/commit/8d9dcf4eea84d65908dc413345676e1d9483d55b](url).
