### ISSUE TITLE
FQNavigation queries crash on non source code models

### ISSUE THREAD

**Issue by NicolasAnquetil** [moosetechnology/Midas#36]
tried with https://github.com/NicolasAnquetil/OpenStackInMoose.git

There is for example relationships between ResourceType and Feature

**Comment by ClotildeToullec** [comment]
Isn't it because this MM does not define sources and targets ?
Navigation queries select properties that are associations , i.e. for which opposite isSource or isTarget depending on the direction.

**Comment by NicolasAnquetil** [comment]
Yes it is
But if one cannot do navigation queries, the other queries (property, scope, ...) should still be available

**Comment by ClotildeToullec** [comment]
Ah ok, I didn't get it, I thought the problem was that no navigation was available.
We changed Navigation queries and I adapted the browser.
It seems to be working now.
