### ISSUE TITLE
Rename MooseRootBrowser and/or MooseModelBrowser

### ISSUE THREAD

**Issue by NicolasAnquetil** [moosetechnology/Midas#39]
the two names are too similar and it's hard to guess what they do.

MooseModelBrowser should allow to browse Models, i.e. what MooseRootBrowser currently does

and the current MooseModelBrowser could may be merged with the Properties browser ?
(other issue)
For now, I propose to rename it ModelContent browser

**Comment by badetitou** [comment]
Why not merge the two browsers?

One Model browser, in the toolbar (1) a select field (where we select the model to browse) and (2) the two buttons to import new models.
What is your opinion?

**Comment by NicolasAnquetil** [comment]
Yes, could be a solution.

But still showing the content of the model seems similar to what the Properties browser does (for other entities)

**Comment by badetitou** [comment]
We have to take care because you have to keep features like "set root folder", "rename the model", etc.

**Comment by jordanmontt** [comment]
MooseModelBrowser and MooseRootBrowser classes does not exists now in Midas. We should close this?
