### ISSUE TITLE
Browsers should not automatically propagate when they follow

### ISSUE THREAD

**Issue by ClotildeToullec** [moosetechnology/Midas#65]
For example, MooseModelBrowser propagates an empty MooseGroup each time it receives new entities. 
This is because computing new entities changes the selection --> the new selection is propagated.

A test should assert that this does not happen.

**Comment by NicolasAnquetil** [comment]
Not sure what is the status, but browser should only propagate on user action on this very browser.
Whether the browser follows or not is irrelevant, a browser should not propagate something it received

**Comment by ClotildeToullec** [comment]
That's what I meant.
I said "follow" because it's changing selection that can trigger an unwanted propagation and the selection changes only when browsers follow.
But I will change the test to assert that no unwanted propagation happens when in other states than "follow", we never know.

**Comment by ClotildeToullec** [comment]
Commit 5316081a26791c3d8a8ad68d31302b7d002d16f2
