### ISSUE TITLE
There should be a 'Select' by default with 'Follow' and 'Freeze' on every tool

### ISSUE THREAD

**Issue by NicolasAnquetil** [moosetechnology/Midas#7]

**Comment by badetitou** [comment]
What do you mean by "select"? 
Is it propagate?

**Comment by NicolasAnquetil** [comment]
No, highlight
Like freeze, but also highlight the entities coming from outside when they were already present in the tool.
(or maybe we can say that this is the default behaviour of Freeze)

**Comment by NicolasAnquetil** [comment]
See BrowserModeHighlight

**Comment by badetitou** [comment]
The button is implemented.
By default it does the same thing as freeze (I believe it is what we expect).
Now we have to thing for each browser what it does
