### ISSUE TITLE
Add features to Model Root browser

### ISSUE THREAD

**Issue by ClotildeToullec** [moosetechnology/Midas#71]
Rename, delete, export, ... should be available in Model Root Browser.
See Moose Panel features.

- [X] Rename
- [X] Delete
- [X] Export
    - [X] mse
    - [X] Json

**Comment by badetitou** [comment]
I have updated the above comment with the feature to include
It looks like everything is done. 
I think we can close this issue. 
Do you agree @ClotildeToullec? 
Or, maybe let's add the missing feature in the above list
