### ISSUE TITLE
Logger browser and buses

### ISSUE THREAD

**Issue by ClotildeToullec** [moosetechnology/Midas#76]
If a logger is open and a bus is created from another browser, do we want:
- to automatically update the open logger to show the logs of the new bus ?
- to manually make the logger follow this new bus if, and only if, we want to ? In this case, the logger behaves like every other browser.

**Comment by NicolasAnquetil** [comment]
I would :
1) automatically follow the new bus. By default the logger logs all buses
2) allow to follow the buses we want in the logger (like a regular browser)

**Comment by ClotildeToullec** [comment]
Ok, so the logger's behavior is "follow all buses unless configured otherwise".

This triggers another question: if a logger is on "Freeze":
- it does not update when an entity is propagated ? (weird: why have an opened logger in this case ?)
- it does not follow new buses ?
- Both ?

**Comment by NicolasAnquetil** [comment]
I would say 1st solution (normal freeze action)
If the user freezes the logger, he knows what he is doing and why
Let's trust his intelligence
