### ISSUE TITLE
"Accept" button in bus panel not clear

### ISSUE THREAD

**Issue by NicolasAnquetil** [moosetechnology/Midas#80]
I tried to create a new bus, entered the name and then pressed "Accept" but this is not the way to do it

Anyway, by just clicking somewhere else on the window title for example, the same behavior than accept can be achieve. So may be it is not very useful ?

**Comment by NicolasAnquetil** [comment]
All the more confusing because "accept" can also serve as a "cancel" button ...
Maybe just "Close" would help

**Comment by ClotildeToullec** [comment]
Ok, that's right. 
We need a button anyway because clicking on the window title only hides the bus panel, it does not close it.
I opened [an issue](https://github.com/pharo-spec/Spec/issues/901) in Spec about it.
I'll change the button label to avoid misunderstanding.

**Comment by NicolasAnquetil** [comment]
Instead of a button in the tool bar, we could think of other means to add buses

For example an extra empty line in the list of buses with a + button, or with a text field to enter a name and press return ...

I don't really like the actual button

**Comment by jordanmontt** [comment]
Maybe we can add an "Add" label in the side of the plus button "+". And change the name from "Accept" to "Close".

![image](https://user-images.githubusercontent.com/33934979/116712099-06a31500-a9c3-11eb-8ae6-05cb122e8725.png)

**Comment by ClotildeToullec** [comment]
I don't think the 'Accept' button is needed anymore. The popover has been fixed so clicking outside of it *does* close it now.

Now, the '+' button, I don't know: can Spec text fields accept when pressing enter or Cmd+S now ? It would be cool to avoid clicking.

**Comment by jordanmontt** [comment]
> 
> 
> I don't think the 'Accept' button is needed anymore. The popover has been fixed so clicking outside of it _does_ close it now.
> 
> Now, the '+' button, I don't know: can Spec text fields accept when pressing enter or Cmd+S now ? It would be cool to avoid clicking.

Yes! when you click enter is the same as clicking in the adding button.
