### ISSUE TITLE
Error when trying to open Query browser

### ISSUE THREAD

**Issue by NicolasAnquetil** [moosetechnology/Midas#82]
On a Java model created from MSE (see attached files: screenshot of error and mse file)
![queryBrowser](https://user-images.githubusercontent.com/14889146/87926262-ba18c980-ca81-11ea-8a50-5b5e1271d154.png)
[lanModl.zip](https://github.com/moosetechnology/Midas/files/4946970/lanModl.zip)

**Comment by ClotildeToullec** [comment]
I cannot reproduce it, are you sure your version of FamixQueries is up to date ?
This method was introduced in [this commit](https://github.com/moosetechnology/FamixQueries/commit/1a522e6b73acb372a878afe882adde399c1717bd).

**Comment by jordanmontt** [comment]
This is old. Maybe we can close it? @NicolasAnquetil

**Comment by jordanmontt** [comment]
I will close this because I cannot reproduce it and because is quite old.
