### ISSUE TITLE
Overview browser lacks a scroll bar

### ISSUE THREAD

**Issue by NicolasAnquetil** [moosetechnology/Midas#84]
When there are too many browser, the last ones are not visible/accessible

**Comment by jordanmontt** [comment]
I testes it in it is working fine for my. I opened a large number of browsers and I get the scrollbar. 
See:
![image](https://user-images.githubusercontent.com/33934979/116704929-7dd4ab00-a9bb-11eb-89c5-8f57b600e810.png)

**Comment by jordanmontt** [comment]
I will close this because I was not able to reproduce this
