### ISSUE TITLE
Too many metamodel options in ModelBrowser

### ISSUE THREAD

**Issue by NicolasAnquetil** [moosetechnology/Midas#87]
The list of available metamodels in the Model browser when wanting to import a model is enormous.

Many of these are useless here, e.g. all test metamodels
They should be removed from the list

**Comment by NicolasAnquetil** [comment]
Good first implementation,
But the user could want to name a meatamodel with 'Test'.
For example: 'JavaWithTestosteroneMetamodel' :-)

Would be nice to find a more sophisticated solution

**Comment by ClotildeToullec** [comment]
Yes, I agree, it's a bit of a dumb solution.
I can improve it, but I need a discriminating criterion and I don't really know what to choose:
"for tests" or not, "concrete" or not, ... ? Do you have a suggestion ?

(I'd really enjoy to see what a 'JavaWithTestosteroneMetamodel' would look like ^^
"A strong metamodel, for your masculine model, Bro ! :muscle: ")

**Comment by ClotildeToullec** [comment]
Fixed https://github.com/moosetechnology/Midas/commit/a9408daec922289b7941f54259bd07d590a12d2c
