### ISSUE TITLE
Browsers propagate even when frozen.

### ISSUE THREAD

**Issue by ClotildeToullec** [moosetechnology/Midas#90]
This behavior seems weird: a frozen browser cannot receive but it can propagate entities.
Maybe we should change this and isolate completely a frozen browser from communications.

**Comment by NicolasAnquetil** [comment]
No I think it is the correct behaviour
That way we can have a list of entities in a frozen browser and explore them one after the other in other browsers by having the frozen one propagating its entities.
To isolate it completely, we can ignore all buses, so we can have both behaviors
