### ISSUE TITLE
adding a bus , strange design 

### ISSUE THREAD

**Issue by CafeKrem** [moosetechnology/Midas#94]
<img width="965" alt="Capture d’écran 2021-03-26 à 09 37 13" src="https://user-images.githubusercontent.com/36420329/112604858-ee196b00-8e16-11eb-86f8-37ea7c25f6e4.png">

in order to add a bus we need to do:
1 - write the name of your bus 
2 - click on '+' button
3 - click on accept button

I think an easier way is to:
1 - write the name of your bus 
2 - click on accept button

**Comment by NicolasAnquetil** [comment]
yes
Less clicks please
halt clickodrome

**Comment by ClotildeToullec** [comment]
Same issue as #80

**Comment by ClotildeToullec** [comment]
Fixed by #80
